import React from 'react';

const breeds = [
    'Affen Pinscher',
    'Afghan Hound',
    'Airedale Terrier',
    'Akita',
    'Alaskan Klee Kai',
    'Alaskan Malamute',
    'American Bulldog',
    'American English Coonhound',
    'American Eskimo Dog',
    'American Foxhound',
    'American Pitbull Terrier',
    'American Staffordshire Terrier',
    'American Water Spaniel',
    'Anatolian Shepherd Dog',
    'Appenzeller Sennenhunde',
    'Australian Cattle Dog',
    'Australian Kelpie',
    'Australian Shepherd',
    'Australian Terrier',
    'Azawakh Barbet',
    'Basenji',
    'BassetHound',
    'Beagle',
    'Bearded Collie',
    'BedlingtonT errier',
    'Belgian Malinois',
    'Belgian Sheepdog',
    'Belgian Tervuren',
    'Berger Picard',
    'Bernedoodle',
    'Bernese Mountain Dog',
    'Bichon Frise',
    'Black and Tan Coonhound',
    'Black Mouth Cur',
    'Black Russian Terrier',
    'Bloodhound',
    'BlueLacy',
    'Bluetick Coonhound',
    'Boerboel',
    'Bolognese',
    'Border Collie',
    'Border Terrier',
    'Borzoi',
    'Boston Terrier',
    'Daschund',
    'Labrador',
    'Bulldog',
    'Germen Sheperd',
    'Chihuaha']

export default breeds
